### ISSUE TITLE
Not working with android 11

### ISSUE THREAD

**Issue by fmeneuhe** [Zaid-Mirza/AttachmentManager#3]
Hi,
First of all thanks foyr your great lib.
There is an issue with Android 11, the Gallery and Photo does not work.
Best regards

**Comment by Zaid-Mirza** [comment]
What is the exact issue that you are facing? Please provide more details @fmeneuhe

**Comment by fmeneuhe** [comment]
When I select either Gallery or Photo it does nothing.

**Comment by Zaid-Mirza** [comment]
I have updated the lib. Please make sure you have latest version. For Android 11, the package visibility is changed so you need to add following in your Manifest file.

```xml
<queries>
        <intent>
            <action android:name="android.intent.action.OPEN_DOCUMENT" />
            <!-- If you don't know the MIME type in advance, set "mimeType" to "*/*". -->
            <data android:mimeType="*/*" />
        </intent>
        <intent>
            <action android:name="android.intent.action.PICK" />
            <!-- If you don't know the MIME type in advance, set "mimeType" to "*/*". -->
            <data android:mimeType="*/*" />
        </intent>
    </queries>
```
